namespace BgGame_Lib.Tests;

using System.Text.Json;
using System.Text.Json.Serialization;

/// <summary>
/// Loads the committed cross-language test vectors
/// (<c>spec/verifiable-dice-vectors.json</c>) that pin the verifiable-dice
/// algorithm. The file is generated by an independent Python reference and
/// cross-checked against openssl; the pinning tests here reproduce it, so a
/// green run means the C# implementation agrees with a separate implementation
/// of the same public spec. Consumed in place — one source of truth — mirroring
/// BgInference's <c>ParityFixture</c> convention.
/// </summary>
internal static class VerifiableDiceVectors
{
    // From the test assembly's output dir up to the BgGame_Lib repo root, then
    // into spec/ (bin/Debug/net10.0 → four levels up).
    private static readonly string VectorsPath = Path.GetFullPath(
        Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "spec", "verifiable-dice-vectors.json"));

    private static readonly Lazy<VectorFile> _file = new(() =>
        JsonSerializer.Deserialize<VectorFile>(System.IO.File.ReadAllText(VectorsPath))
            ?? throw new InvalidDataException($"'{VectorsPath}' deserialized to null."));

    /// <summary>The parsed vectors file (header + all vectors).</summary>
    internal static VectorFile File => _file.Value;

    /// <summary>All pinned vectors.</summary>
    internal static IReadOnlyList<DiceVector> All => File.Vectors;

    /// <summary>Find a vector by its unique label.</summary>
    internal static DiceVector Named(string label) => All.Single(v => v.Label == label);
}

internal sealed record VectorFile
{
    [JsonPropertyName("format_version")] public int FormatVersion { get; init; }
    [JsonPropertyName("vectors")] public IReadOnlyList<DiceVector> Vectors { get; init; } = [];
}

internal sealed record DiceVector
{
    [JsonPropertyName("label")] public string Label { get; init; } = "";
    [JsonPropertyName("key_hex")] public string KeyHex { get; init; } = "";
    [JsonPropertyName("context")] public string Context { get; init; } = "";
    [JsonPropertyName("commitment_hex")] public string CommitmentHex { get; init; } = "";
    [JsonPropertyName("block0_hex")] public string Block0Hex { get; init; } = "";
    [JsonPropertyName("rolls")] public IReadOnlyList<IReadOnlyList<int>> Rolls { get; init; } = [];
    [JsonPropertyName("rejected_byte_offsets")] public IReadOnlyList<int> RejectedByteOffsets { get; init; } = [];

    /// <summary>The pinned rolls as dice tuples.</summary>
    internal IEnumerable<(int Die1, int Die2)> RollTuples => Rolls.Select(r => (r[0], r[1]));
}
